# Generated by Django 5.0.6 on 2024-06-23 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDePedra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Chapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('comprimento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('largura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('espessura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('defeitos_superficiais', models.TextField(blank=True, null=True)),
                ('qr_code', models.CharField(max_length=255)),
                ('localizacao_estoque', models.CharField(max_length=100)),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('data_saida', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('tipo_de_pedra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.tipodepedra')),
            ],
        ),
    ]
