# Generated by Django 5.0.6 on 2024-06-23 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalizacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('localizacao', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='chapa',
            name='localizacao_estoque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.localizacaoestoque'),
        ),
        migrations.CreateModel(
            name='Sobra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprimento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('largura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('espessura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('geometria', models.TextField()),
                ('qr_code', models.CharField(max_length=255)),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('chapa_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.chapa')),
                ('localizacao_estoque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.localizacaoestoque')),
            ],
        ),
        migrations.CreateModel(
            name='EntradaSaida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('quantidade', models.PositiveIntegerField()),
                ('descricao', models.TextField()),
                ('chapa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.chapa')),
                ('sobra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.sobra')),
            ],
        ),
    ]
